const imgConfig = {
    background: 'images/bg_day.png',
    ground: 'images/ground.png',
    //
    big_number0: 'images/font_0.png',
    big_number1: 'images/font_1.png',
    big_number2: 'images/font_2.png',
    big_number3: 'images/font_3.png',
    big_number4: 'images/font_4.png',
    big_number5: 'images/font_5.png',
    big_number6: 'images/font_6.png',
    big_number7: 'images/font_7.png',
    big_number8: 'images/font_8.png',
    big_number9: 'images/font_9.png',
    //
    small_number0: 'images/number_score_00.png',
    small_number1: 'images/number_score_01.png',
    small_number2: 'images/number_score_02.png',
    small_number3: 'images/number_score_03.png',
    small_number4: 'images/number_score_04.png',
    small_number5: 'images/number_score_05.png',
    small_number6: 'images/number_score_06.png',
    small_number7: 'images/number_score_07.png',
    small_number8: 'images/number_score_08.png',
    small_number9: 'images/number_score_09.png',
    //
    pipe_up: 'images/pipe_up.png',
    pipe_down: 'images/pipe_down.png',
    coin: 'images/coin.png',
    // title: 'images/name.png',
    // start: 'images/start.png',
    // sceneEnd: 'images/gameOver.png',
    //
    palyer_idle1: 'images/bird1_0.png',
    palyer_idle2: 'images/bird1_1.png',
    palyer_idle3: 'images/bird1_2.png',
}
